const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const vm=require('vm');const path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function context(profile=null,state={transactions:[],recurring:[],cards:[]}){const c={onboardingProfile:profile,state};vm.createContext(c);for(const name of ['inferAccountFromPayment','normalizeUserBanks','userBanks','userPaymentMethods'])vm.runInContext(html.split('\n').find(l=>l.startsWith('function '+name+'(')),c);return c}
const plain=v=>JSON.parse(JSON.stringify(v));
test('New account has no creator banks; every chosen institution gets six expense methods',()=>{const c=context({banks:['Santander','Sicredi']});const p=plain(c.userPaymentMethods());assert.equal(p.length,14);for(const b of ['Santander','Sicredi'])for(const k of ['Crédito','Débito','Pix','Boleto bancário','Transferência bancária','Depósito'])assert.ok(p.includes(b+' - '+k));assert.ok(!p.some(x=>x.includes('Itaú')));assert.deepEqual(plain(context().userPaymentMethods()),['Dinheiro','Outro']);});
test('Normalizes duplicate names and supports no bank',()=>{const c=context();assert.deepEqual(plain(c.normalizeUserBanks(' Itaú, ITAU; Sicredi\nSicredi')),['Itaú','Sicredi']);assert.deepEqual(plain(c.normalizeUserBanks('Sem banco')),[]);});
test('Account inference handles custom institutions and all supported methods',()=>{const c=context();for(const k of ['Crédito','Débito','Pix','Boleto bancário','Transferência bancária','Depósito'])assert.equal(c.inferAccountFromPayment('Banco novo - '+k),'Banco novo');assert.equal(c.inferAccountFromPayment('Dinheiro'),'');});
test('Legacy edit retains payment even after removing bank from choices',()=>{const c=context({banks:['Sicredi']});assert.ok(c.userPaymentMethods(false,'Itaú - Pix').includes('Itaú - Pix'));assert.ok(!c.userPaymentMethods().includes('Itaú - Pix'));assert.ok(c.userPaymentMethods(true).includes('Sicredi - Depósito'));});
test('Existing users infer only their own institutions; explicit bank list takes precedence',()=>{const state={transactions:[{payment:'Inter - Pix'}],recurring:[{account:'Bradesco'}],cards:[]};assert.deepEqual(plain(context(null,state).userBanks()),['Inter','Bradesco']);assert.deepEqual(plain(context({banks:[]},state).userBanks()),[]);});
test('Official catalog search handles accents, brand aliases, CNPJ and cooperatives',()=>{const c=context();c.bankCatalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../bcb-institutions.json'))).institutions;for(const name of ['bankSearchKey','bankPresentation','searchBankCatalog'])vm.runInContext(html.split('\n').find(l=>l.startsWith('function '+name+'(')),c);assert.ok(c.bankCatalog.length>1500);for(const term of ['itau','santander','nubank','sicredi','picpay','mercado pago'])assert.ok(c.searchBankCatalog(term).length,term);assert.ok(c.searchBankCatalog('NU PAGAMENTOS').some(r=>r.type==='Instituição de Pagamento'));const r=c.bankCatalog[0];assert.ok(c.searchBankCatalog(r.id).some(x=>x.id===r.id));assert.equal(c.searchBankCatalog('').length,0);assert.equal(c.searchBankCatalog('instituicao inexistente abcxyz').length,0);assert.ok(c.searchBankCatalog('banco').length<=12);});
test('Bank chips exclude legacy payment types and service names',()=>{const c=context({banks:['Itaú','Transferência bancária','Pix','Uber','Amazon','Amazon (Bradesco)','C6 Bank']});assert.deepEqual(plain(c.userBanks()),['Itaú','Bradesco','C6 Bank']);const legacy=context(null,{transactions:[{account:'Pix'},{account:'Transferência bancária'},{account:'Uber'},{payment:'Itaú - Pix'}],recurring:[],cards:[{name:'Amazon (Bradesco)'}]});assert.deepEqual(plain(legacy.userBanks()),['Itaú','Bradesco']);assert.ok(!c.userPaymentMethods().some(p=>p.startsWith('Pix - ')));});
